.. automodule:: pystoch.utilities.exceptions
   :members:


